Zero amount orders allowed
netlify/gocommerce-js pull request #12
Opened 2017-11-22 18:35 UTC by pukhalski

2017-11-23 07:56 UTC, biilmann requested changes

2017-11-23 07:56 UTC, biilmann commented on src/index.js
> +    if (order_id && amount !== undefined && provider && (stripe_token || (paypal_payment_id && paypal_user_id))) {
lets change this to `amount != null` so we cancel on both `null` and `undefined` but not on `0`

2018-12-10 22:46 UTC, bcomnes commented on src/index.js
> +    if (order_id && amount !== undefined && provider && (stripe_token || (paypal_payment_id && paypal_user_id))) {
```suggestion
    if (order_id && amount != null && provider && (stripe_token || (paypal_payment_id && paypal_user_id))) {
```

2018-12-10 22:47 UTC, bcomnes commented on src/index.js
> +    if (order_id && amount !== undefined && provider && (stripe_token || (paypal_payment_id && paypal_user_id))) {
whelp, that didn't work.

2018-12-10 22:57 UTC, closed without merging