convert from netlify to go
netlify/gocommerce-js pull request #3
Opened 2017-03-08 20:34 UTC by rybit

2017-03-09 05:41 UTC, verythorough requested changes
Found a few instances of "Go Commerce" with an extra space. I don't have commit access on this repo, so I went the easy way and just made comments. 😈

2017-03-09 05:41 UTC, verythorough commented on README.md
> +# Go Commerce JS
Remove space

2017-03-09 05:41 UTC, verythorough commented on README.md
> +This is a JS client library for [Go Commerce](https://github.com/netlify/gocommerce) API.
Remove space

2017-03-09 05:41 UTC, verythorough commented on README.md
> +You can use Go Commerce JS together with [GoTrue](https://github.com/netlify/gotrue) to let users log in and claim view order history.
Remove space

2017-03-09 19:10 UTC, verythorough commented
Looks good to me! Though I can't fully confirm the code part is good. I assume npm/etc. handles the name change so projects using netlify-commerce-js don't break?

2017-03-13 20:13 UTC, bdougie commented
Authlify needs to be changed to goTrue in the readme

2017-03-13 20:16 UTC, bdougie commented
also src/index.js references `NetlifyCommerce` and `netlify.commerce`

2017-03-13 20:20 UTC, rybit commented
I am not seeing those @bdougie

2017-03-13 20:22 UTC, bdougie commented
my bad, I was looking at master. This is good

2017-03-13 20:23 UTC, merged